#Requires -Version 5.1
<#
  DotfilesExport.ps1 - A-side dotfiles source-state export + chezmoi.exe payload.
  Windows PowerShell 5.1 compatible: no PS7-only syntax.

  Export-OSyncDotfiles -Config -StagingDir

    1. Validates <toolRoot>\manifests\dotfiles is a legal chezmoi source state:
       the directory must exist, and NO .chezmoiexternal* file may be present
       anywhere under it (recursive). Externals fetch content from the network
       at apply time, which the offline B side does not have - the export
       rejects them up front ("offline does not support externals").
    2. robocopy /MIR the source state to <staging>\dotfiles\source.
    3. <toolRoot>\manifests\dotfiles.toml (when present) is copied to
       <staging>\dotfiles\chezmoi.toml; otherwise a minimal template with an
       empty [data] section and commented examples is generated.
    4. Downloads chezmoi (config.pins.chezmoi.url; default v2.72.0 GitHub
       release zip) and verifies its sha256:
         - config.pins.chezmoi.sha256 == "PIN-ME" -> prints the ACTUAL hash
           and exits non-zero (prompt to pin it into the config),
         - mismatch -> aborts naming expected vs actual,
         - match -> extracts chezmoi.exe to
           <staging>\runtime\chezmoi\chezmoi.exe.
       The zip is downloaded only when missing from the staging dir, so a
       PIN-ME run followed by a pinned re-run performs exactly ONE download.

  The chezmoi symlink feature is NEVER enabled anywhere in this module
  (avoids the Windows developer-mode prerequisite).

  Returns the export report as a PSCustomObject.

  Helpers (all auto-exported by the OfflineSync module's *-OSync* rule):
    Get-OSyncFileSha256, Assert-OSyncDotfilesSource, Get-OSyncChezmoiTomlContent,
    Expand-OSyncChezmoiZip
#>

function Get-OSyncFileSha256 {
    <#
      Streams SHA256 over a file without loading it into memory (1 MB buffer).
      Returns the lowercase hex digest. Shared with todo 10 (appInstaller
      payloads) - same pattern as RepoContract's private Get-RcSha256.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
        throw "Get-OSyncFileSha256: file not found: '$Path'."
    }

    $sha = [System.Security.Cryptography.SHA256]::Create()
    $stream = $null
    try {
        $stream = [System.IO.File]::OpenRead($Path)
        $buffer = New-Object byte[] 1048576
        while ($true) {
            $read = $stream.Read($buffer, 0, $buffer.Length)
            if ($read -le 0) { break }
            [void]$sha.TransformBlock($buffer, 0, $read, $null, 0)
        }
        [void]$sha.TransformFinalBlock($buffer, 0, 0)
        return ([System.BitConverter]::ToString($sha.Hash).Replace('-', '').ToLowerInvariant())
    }
    finally {
        if ($null -ne $stream) { $stream.Dispose() }
        $sha.Dispose()
    }
}

function Assert-OSyncDotfilesSource {
    <#
      Validates that <SourceDir> is a legal chezmoi source state for the
      offline pipeline:
        - the directory must exist,
        - no .chezmoiexternal* FILE may exist anywhere under it (recursive).
      Externals require network access at apply time (chezmoi fetches the
      external content when running `chezmoi apply`), so they are rejected
      here with an explicit error naming the offending file(s).
      Returns $true on success; throws otherwise.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$SourceDir
    )

    if (-not (Test-Path -LiteralPath $SourceDir -PathType Container)) {
        throw "Export-OSyncDotfiles: dotfiles source directory not found: '$SourceDir'."
    }

    $externals = @(Get-ChildItem -LiteralPath $SourceDir -Recurse -File -Filter '.chezmoiexternal*' -ErrorAction SilentlyContinue)
    if ($externals.Count -gt 0) {
        $names = ($externals | ForEach-Object { $_.FullName }) -join ', '
        throw "Export-OSyncDotfiles: offline does not support externals - found .chezmoiexternal* file(s): $names. Remove them from the source state."
    }
    return $true
}

function Get-OSyncChezmoiTomlContent {
    <#
      Minimal chezmoi config template for the offline B side: an empty [data]
      section (template variables for source files) plus commented examples.
      Deliberately contains NO symlink-related settings - the symlink feature
      is never enabled (avoids the Windows developer-mode prerequisite).
    #>
    [CmdletBinding()]
    param()

    return @'
# chezmoi.toml - generated by PakageSync Export-OSyncDotfiles (offline export).
# Applied on the B side with:
#   chezmoi --source <work>\dotfiles\source --config <work>\dotfiles\chezmoi.toml apply
# No special filesystem features are enabled (avoids the Windows
# developer-mode prerequisite).

[data]
# Template data available to source files as {{ .data.<key> }}.
# Example:
#   name = "user"
#   email = "user@example.com"
'@
}

function Expand-OSyncChezmoiZip {
    <#
      Extracts the chezmoi.exe entry from the downloaded release zip into
      <Destination>\chezmoi.exe. Only the exe entry is extracted (the zip
      also carries LICENSE/README). Throws when the entry is missing.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$ZipPath,

        [Parameter(Mandatory = $true)]
        [string]$Destination
    )

    Add-Type -AssemblyName System.IO.Compression.FileSystem -ErrorAction Stop
    $zip = [System.IO.Compression.ZipFile]::OpenRead($ZipPath)
    try {
        $entry = $zip.Entries | Where-Object { $_.Name -ieq 'chezmoi.exe' } | Select-Object -First 1
        if ($null -eq $entry) {
            throw "Expand-OSyncChezmoiZip: no 'chezmoi.exe' entry found in '$ZipPath'."
        }
        if (-not (Test-Path -LiteralPath $Destination -PathType Container)) {
            New-Item -ItemType Directory -Path $Destination -Force | Out-Null
        }
        $target = Join-Path $Destination 'chezmoi.exe'
        [System.IO.Compression.ZipFileExtensions]::ExtractToFile($entry, $target, $true)
        return $target
    }
    finally {
        $zip.Dispose()
    }
}

function Export-OSyncDotfiles {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        $Config,

        [Parameter(Mandatory = $true)]
        [string]$StagingDir
    )

    # --- 1. validate the chezmoi source state (dir exists, no externals) ---
    # config.paths.* are tool-root-relative INPUT manifests (never
    # config.repoRoot - that is the output landing dir).
    $sourceDir = Resolve-OSyncConfigPath -Config $Config -Path $Config.paths.dotfilesSource
    $null = Assert-OSyncDotfilesSource -SourceDir $sourceDir
    # Write-OSyncLog RETURNS the JSONL path - pipe to Out-Null so the export
    # report object is the ONLY thing this function emits (same pattern as
    # WingetExport.ps1 / PipExport.ps1 / NpmExport.ps1).
    Write-OSyncLog -Category 'dotfiles' -Level Info -Message "dotfiles source state validated: '$sourceDir'" -Config $Config | Out-Null

    # --- 2. robocopy /MIR to <staging>\dotfiles\source ---
    $dotfilesDir = Join-Path $StagingDir 'dotfiles'
    $sourceTarget = Join-Path $dotfilesDir 'source'
    $null = Invoke-OSyncRobocopy -Source $sourceDir -Destination $sourceTarget -ExtraArgs @('/MIR')
    Write-OSyncLog -Category 'dotfiles' -Level Info -Message "dotfiles source state copied to '$sourceTarget'" -Config $Config | Out-Null

    # --- 3. chezmoi.toml: copy manifests\dotfiles.toml or generate a template ---
    $tomlSource = Resolve-OSyncConfigPath -Config $Config -Path 'manifests\dotfiles.toml'
    $tomlTarget = Join-Path $dotfilesDir 'chezmoi.toml'
    if (Test-Path -LiteralPath $tomlSource -PathType Leaf) {
        Copy-Item -LiteralPath $tomlSource -Destination $tomlTarget -Force
        Write-OSyncLog -Category 'dotfiles' -Level Info -Message "Copied 'manifests\dotfiles.toml' to '$tomlTarget'" -Config $Config | Out-Null
    }
    else {
        $template = Get-OSyncChezmoiTomlContent
        [System.IO.File]::WriteAllText($tomlTarget, $template, (New-Object System.Text.UTF8Encoding($true)))
        Write-OSyncLog -Category 'dotfiles' -Level Info -Message "Generated minimal chezmoi.toml template at '$tomlTarget' (no manifests\dotfiles.toml present)" -Config $Config | Out-Null
    }

    # --- 4. chezmoi.exe payload: download -> sha256 gate -> extract ---
    $runtimeChezmoiDir = Join-Path (Join-Path $StagingDir 'runtime') 'chezmoi'
    $zipPath = Join-Path $runtimeChezmoiDir 'chezmoi.zip'
    $url = [string]$Config.pins.chezmoi.url
    $expected = [string]$Config.pins.chezmoi.sha256
    $isPinMe = ($expected -eq 'PIN-ME')

    # Download only when the zip is missing: a PIN-ME run followed by a pinned
    # re-run (same staging dir) performs exactly ONE download, and a retry
    # after a hash failure does not re-fetch the same bytes.
    if (-not (Test-Path -LiteralPath $zipPath -PathType Leaf)) {
        Write-OSyncLog -Category 'dotfiles' -Level Info -Message "Downloading chezmoi from '$url' -> '$zipPath'" -Config $Config | Out-Null
        $null = Invoke-OSyncDownload -Uri $url -OutFile $zipPath
    }
    else {
        Write-OSyncLog -Category 'dotfiles' -Level Info -Message "Reusing existing download '$zipPath'" -Config $Config | Out-Null
    }

    $actualHash = Get-OSyncFileSha256 -Path $zipPath

    if ($isPinMe) {
        # PIN-ME: print the actual hash and exit non-zero (prompt to pin).
        Write-Host "Export-OSyncDotfiles: config.pins.chezmoi.sha256 is 'PIN-ME'."
        Write-Host "Actual sha256 of '$zipPath' is: $actualHash"
        Write-Host "Pin it into config\packagesync.json (pins.chezmoi.sha256) and re-run."
        Write-OSyncLog -Category 'dotfiles' -Level Error -Message "PIN-ME: actual chezmoi sha256 is $actualHash - pin it into the config and re-run." -Data @{ actualSha256 = $actualHash } -Config $Config | Out-Null
        throw "Export-OSyncDotfiles: config.pins.chezmoi.sha256 is 'PIN-ME' - pin the real sha256 ($actualHash) into config\packagesync.json and re-run."
    }

    if ($actualHash -ne $expected) {
        Write-OSyncLog -Category 'dotfiles' -Level Error -Message "chezmoi sha256 mismatch: expected '$expected', got '$actualHash'." -Data @{ expected = $expected; actual = $actualHash } -Config $Config | Out-Null
        throw "Export-OSyncDotfiles: chezmoi sha256 mismatch for '$zipPath': expected '$expected', got '$actualHash'. Aborting - the download is not the pinned artifact."
    }

    $exePath = Expand-OSyncChezmoiZip -ZipPath $zipPath -Destination $runtimeChezmoiDir
    Write-OSyncLog -Category 'dotfiles' -Level Info -Message "chezmoi.exe extracted to '$exePath' (sha256 $actualHash)" -Data @{ sha256 = $actualHash } -Config $Config | Out-Null

    # --- 5. success report ---
    $report = [ordered]@{
        category = 'dotfiles'
        status   = 'ok'
        source   = $sourceDir
        target   = $sourceTarget
        chezmoi  = [ordered]@{
            version = [string]$Config.pins.chezmoi.version
            url     = $url
            sha256  = $actualHash
            exePath = $exePath
        }
    }
    Write-OSyncLog -Category 'dotfiles' -Level Info -Message "dotfiles export complete: source at '$sourceTarget', chezmoi.exe at '$exePath'." -Data @{ sha256 = $actualHash } -Config $Config | Out-Null

    return [pscustomobject]$report
}